export const GET_USER_ERRORS = "GET_USER_ERRORS";
export const GET_GOAL_ERRORS = "GET_GOAL_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CREATE_GOAL_MODAL = "SET_CREATE_GOAL_MODAL";
export const SET_GOALS = "SET_GOALS";
export const SET_UPDATE_GOAL_MODAL = "SET_UPDATE_GOAL_MODAL";

export const GET_SEARCH_USERS = "GET_SEARCH_USERS";
export const SET_VIEW_USER = "SET_VIEW_USER";

export const SET_FOLLOWING = "SET_FOLLOWING";